### ISSUE TITLE
Compilation error "inconsistent definitions for C.struct_Buffer"

### ISSUE THREAD

**Issue by ElMaxo** [bakape/thumbnailer#48]
With go version go1.10.2 linux/amd64 on Ubuntu 18.04 i get compilation error from title. 
// #include "thumbnailer.h" at cover_art.go fixes the issue

**Comment by bakape** [comment]
Compiled successfully with a stock 18.04 virtual machine. With stock go version (1.10.4). Compiles fine, but all tests fail. Odd.

**Comment by bakape** [comment]
>// #include "thumbnailer.h"

And this line should have no effect as all C comments are concatenated package-wide during compilation.

**Comment by bakape** [comment]
Same result with go 1.11.5 on 18.04. This runs fine on Debian both stable and testing. Might be some compiler or library quirk of 18.04. I'll test on 18.10.

**Comment by bakape** [comment]
Also works fine on Ubuntu 18.10 with stock go version 1.10.4. Writing this off as a bug in 18.04 on the Ubuntu side.
